In [1]:
import pandas as pd
import mysql.connector

In [2]:
from config import MYSQL_CONFIG

config = MYSQL_CONFIG.copy()
config["database"] = "bank_staging"

conn = mysql.connector.connect(**config)

print("Connected successfully")

Connected successfully

In [3]:
from sqlalchemy import create_engine
from config import MYSQL_CONFIG

In [4]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL
from config import MYSQL_CONFIG

db_url = URL.create(
    drivername="mysql+mysqlconnector",
    username=MYSQL_CONFIG["user"],
    password=MYSQL_CONFIG["password"],
    host=MYSQL_CONFIG["host"],
    port=MYSQL_CONFIG["port"],
    database="bank_dw"
)

engine = create_engine(db_url)

In [5]:
print("Connection configuration loaded")

Connection configuration loaded

In [6]:
query = """
SELECT *
FROM stg_customers;
"""

df = pd.read_sql(query, conn)

print(df.shape)

C:\Users\piyus\AppData\Local\Temp\ipykernel_39400\1462347402.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

(15, 20)

In [7]:
df.head()

,customer_id,customer_number,first_name,middle_name,last_name,date_of_birth,gender,email,phone,customer_type,customer_status,registration_date,risk_category,kyc_status,home_branch_id,created_at,updated_at,source_system,batch_id,loaded_at
0,1,CUST000001,Amit,None,Sharma,1992-05-14,MALE,amit.sharma@example.com,9000000001,INDIVIDUAL,ACTIVE,2021-06-15,LOW,VERIFIED,1,2026-08-26 03:03:52,2026-08-26 03:03:52,MYSQL_OLTP,1001,2026-08-28 01:00:02
1,2,CUST000002,Priya,None,Patil,1995-09-22,FEMALE,priya.patil@example.com,9000000002,INDIVIDUAL,ACTIVE,2022-01-10,LOW,VERIFIED,2,2026-08-26 03:03:52,2026-08-26 03:03:52,MYSQL_OLTP,1001,2026-08-28 01:00:02
2,3,CUST000003,Rahul,None,Mehta,1988-11-03,MALE,rahul.mehta@example.com,9000000003,PREMIUM,ACTIVE,2020-03-18,MEDIUM,VERIFIED,1,2026-08-26 03:03:52,2026-08-26 03:03:52,MYSQL_OLTP,1001,2026-08-28 01:00:02
3,4,CUST000004,Sneha,None,Iyer,1997-02-11,FEMALE,sneha.iyer@example.com,9000000004,INDIVIDUAL,ACTIVE,2023-07-25,LOW,PENDING,8,2026-08-26 03:03:52,2026-08-26 03:03:52,MYSQL_OLTP,1001,2026-08-28 01:00:02
4,5,CUST000005,Vikas,None,Verma,1985-12-19,MALE,vikas.verma@example.com,9000000005,CORPORATE,ACTIVE,2019-09-05,HIGH,VERIFIED,5,2026-08-26 03:03:52,2026-08-26 03:03:52,MYSQL_OLTP,1001,2026-08-28 01:00:02

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        15 non-null     int64
 1   customer_number    15 non-null     str
 2   first_name         15 non-null     str
 3   middle_name        0 non-null      object
 4   last_name          15 non-null     str
 5   date_of_birth      15 non-null     object
 6   gender             15 non-null     str
 7   email              15 non-null     str
 8   phone              15 non-null     str
 9   customer_type      15 non-null     str
 10  customer_status    15 non-null     str
 11  registration_date  15 non-null     object
 12  risk_category      15 non-null     str
 13  kyc_status         15 non-null     str
 14  home_branch_id     15 non-null     int64
 15  created_at         15 non-null     datetime64[us]
 16  updated_at         15 non-null     datetime64[us]
 17  source_system      15 non-null     str
 18  batch_id           15 non-null     int64
 19  loaded_at          15 non-null     datetime64[us]
dtypes: datetime64[us](3), int64(3), object(3), str(11)
memory usage: 2.5+ KB

In [9]:
df.isnull().sum()

customer_id           0
customer_number       0
first_name            0
middle_name          15
last_name             0
date_of_birth         0
gender                0
email                 0
phone                 0
customer_type         0
customer_status       0
registration_date     0
risk_category         0
kyc_status            0
home_branch_id        0
created_at            0
updated_at            0
source_system         0
batch_id              0
loaded_at             0
dtype: int64

In [10]:
df.columns.tolist()

['customer_id',
 'customer_number',
 'first_name',
 'middle_name',
 'last_name',
 'date_of_birth',
 'gender',
 'email',
 'phone',
 'customer_type',
 'customer_status',
 'registration_date',
 'risk_category',
 'kyc_status',
 'home_branch_id',
 'created_at',
 'updated_at',
 'source_system',
 'batch_id',
 'loaded_at']

In [11]:
df["cutomer_name"]=(
df["first_name"].fillna("")
+ " " 
+df["last_name"].fillna(""))

df["customer_name"] = (
    df["first_name"].fillna("")
    + " "
    + df["last_name"].fillna("")
).str.strip()

In [12]:
df[["customer_id", "first_name", "last_name", "customer_name"]].head()

   customer_id first_name last_name customer_name
0            1       Amit    Sharma   Amit Sharma
1            2      Priya     Patil   Priya Patil
2            3      Rahul     Mehta   Rahul Mehta
3            4      Sneha      Iyer    Sneha Iyer
4            5      Vikas     Verma   Vikas Verma

In [13]:
df[["customer_id", "first_name", "last_name","cutomer_name"]].head()

   customer_id first_name last_name cutomer_name
0            1       Amit    Sharma  Amit Sharma
1            2      Priya     Patil  Priya Patil
2            3      Rahul     Mehta  Rahul Mehta
3            4      Sneha      Iyer   Sneha Iyer
4            5      Vikas     Verma  Vikas Verma

In [14]:
load_df = df[
    [
        "customer_id",
        "customer_number",
        "customer_name",
        "customer_type",
        "customer_status",
        "risk_category",
        "kyc_status",
        "home_branch_id",
        "registration_date"
    ]
].copy()

load_df=load_df.rename(
    columns={
        "home_branch_id":"branch_id",
        "registration_date": "effective_from"
        
    }
)
load_df["effective_to"]=None

In [15]:
load_df.to_sql(
    "dim_cutomers",
    con=engine,
    if_exists="append",
    index=False)

15

In [16]:
query1="""
select * 
from dim_customer
"""

df1=pd.read_sql(query1,engine)

In [17]:
query1 = """
SELECT *
FROM dim_customer;
"""

df1 = pd.read_sql(query1, engine)

df1.head()

,customer_key,customer_id,customer_number,customer_name,customer_type,customer_status,risk_category,kyc_status,branch_id,city_id,effective_from,effective_to,is_current,created_at,updated_at
0,1,1,CUST000001,Amit Sharma,INDIVIDUAL,INACTIVE,LOW,VERIFIED,1,1,2021-06-15,2026-09-02,0,2026-08-28 03:21:27,2026-09-02 03:12:28
1,2,2,CUST000002,Priya Patil,INDIVIDUAL,ACTIVE,LOW,VERIFIED,2,2,2022-01-10,None,1,2026-08-28 03:21:27,2026-08-28 03:21:27
2,3,3,CUST000003,Rahul Mehta,PREMIUM,ACTIVE,MEDIUM,VERIFIED,1,1,2020-03-18,None,1,2026-08-28 03:21:27,2026-08-28 03:21:27
3,4,4,CUST000004,Sneha Iyer,INDIVIDUAL,ACTIVE,LOW,PENDING,8,8,2023-07-25,None,1,2026-08-28 03:21:27,2026-08-28 03:21:27
4,5,5,CUST000005,Vikas Verma,CORPORATE,ACTIVE,HIGH,VERIFIED,5,5,2019-09-05,None,1,2026-08-28 03:21:27,2026-08-28 03:21:27

In [18]:
records_read = len(df)
records_loaded = len(load_df)

print("Records read:", records_read)
print("Records loaded:", records_loaded)

Records read: 15
Records loaded: 15

In [19]:
records_read = len(df)
records_loaded = len(load_df)

audit_df = pd.DataFrame([{
    "batch_id": 1,
    "pipeline_name": "customer_etl",
    "source_table": "stg_customers",
    "target_table": "dim_customer",
    "records_read": records_read,
    "records_loaded": records_loaded,
    "status": "SUCCESS"
}])

audit_df

,batch_id,pipeline_name,source_table,target_table,records_read,records_loaded,status
0,1,customer_etl,stg_customers,dim_customer,15,15,SUCCESS

In [20]:
audit_df.head()

,batch_id,pipeline_name,source_table,target_table,records_read,records_loaded,status
0,1,customer_etl,stg_customers,dim_customer,15,15,SUCCESS

In [21]:
db_url1 = URL.create(
    drivername="mysql+mysqlconnector",
    username=MYSQL_CONFIG["user"],
    password=MYSQL_CONFIG["password"],
    host=MYSQL_CONFIG["host"],
    port=MYSQL_CONFIG["port"],
    database="bank_staging"
)

engine_staging = create_engine(db_url1)

In [22]:
audit_df.to_sql(
    "etl_audit",
    con=engine_staging,
    if_exists="append",
    index=False
)
print("audit Saved")

audit Saved

In [23]:
reject_df=df[df['customer_number'].isna()].copy()

In [24]:
len(reject_df)

0

In [25]:
valid_df = df[df["customer_number"].notna()].copy()

print("Valid records:", len(valid_df))

Valid records: 15

In [26]:
reject_df["error_reason"] = "Missing customer number"

In [27]:
reject_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        0 non-null      int64
 1   customer_number    0 non-null      str
 2   first_name         0 non-null      str
 3   middle_name        0 non-null      object
 4   last_name          0 non-null      str
 5   date_of_birth      0 non-null      object
 6   gender             0 non-null      str
 7   email              0 non-null      str
 8   phone              0 non-null      str
 9   customer_type      0 non-null      str
 10  customer_status    0 non-null      str
 11  registration_date  0 non-null      object
 12  risk_category      0 non-null      str
 13  kyc_status         0 non-null      str
 14  home_branch_id     0 non-null      int64
 15  created_at         0 non-null      datetime64[us]
 16  updated_at         0 non-null      datetime64[us]
 17  source_system      0 non-null      str
 18  batch_id           0 non-null      int64
 19  loaded_at          0 non-null      datetime64[us]
 20  cutomer_name       0 non-null      str
 21  customer_name      0 non-null      str
 22  error_reason       0 non-null      str
dtypes: datetime64[us](3), int64(3), object(3), str(14)
memory usage: 132.0+ bytes

In [28]:
reject_load_df = pd.DataFrame({
    "batch_id": 1,
    "source_table": "stg_customers",
    "record_id": reject_df["customer_id"],
    "error_type": "MISSING_CUSTOMER_NUMBER",
    "error_message": reject_df["error_reason"]
})

reject_load_df

Empty DataFrame
Columns: [batch_id, source_table, record_id, error_type, error_message]
Index: []

In [29]:
reject_load_df.to_sql(
    "etl_rejects",
    con=engine_staging,
    if_exists="append",
    index=False
)

print("Reject records loaded successfully")

Reject records loaded successfully

In [30]:
source_count = len(df)
target_count = len(load_df)

difference = source_count - target_count

print("Source count:", source_count)
print("Target count:", target_count)
print("Difference:", difference)

Source count: 15
Target count: 15
Difference: 0

In [31]:
df[df["customer_id"] == 1]

,customer_id,customer_number,first_name,middle_name,last_name,date_of_birth,gender,email,phone,customer_type,...,risk_category,kyc_status,home_branch_id,created_at,updated_at,source_system,batch_id,loaded_at,cutomer_name,customer_name
0,1,CUST000001,Amit,None,Sharma,1992-05-14,MALE,amit.sharma@example.com,9000000001,INDIVIDUAL,...,LOW,VERIFIED,1,2026-08-26 03:03:52,2026-08-26 03:03:52,MYSQL_OLTP,1001,2026-08-28 01:00:02,Amit Sharma,Amit Sharma

In [32]:
df.loc[df['customer_id']==1,'customer_status']="INACTIVE"
df[df["customer_id"] == 1]

,customer_id,customer_number,first_name,middle_name,last_name,date_of_birth,gender,email,phone,customer_type,...,risk_category,kyc_status,home_branch_id,created_at,updated_at,source_system,batch_id,loaded_at,cutomer_name,customer_name
0,1,CUST000001,Amit,None,Sharma,1992-05-14,MALE,amit.sharma@example.com,9000000001,INDIVIDUAL,...,LOW,VERIFIED,1,2026-08-26 03:03:52,2026-08-26 03:03:52,MYSQL_OLTP,1001,2026-08-28 01:00:02,Amit Sharma,Amit Sharma

In [33]:
df[df["customer_id"] == 1][
    ["customer_id", "customer_number", "customer_status"]
]

   customer_id customer_number customer_status
0            1      CUST000001        INACTIVE

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        15 non-null     int64
 1   customer_number    15 non-null     str
 2   first_name         15 non-null     str
 3   middle_name        0 non-null      object
 4   last_name          15 non-null     str
 5   date_of_birth      15 non-null     object
 6   gender             15 non-null     str
 7   email              15 non-null     str
 8   phone              15 non-null     str
 9   customer_type      15 non-null     str
 10  customer_status    15 non-null     str
 11  registration_date  15 non-null     object
 12  risk_category      15 non-null     str
 13  kyc_status         15 non-null     str
 14  home_branch_id     15 non-null     int64
 15  created_at         15 non-null     datetime64[us]
 16  updated_at         15 non-null     datetime64[us]
 17  source_system      15 non-null     str
 18  batch_id           15 non-null     int64
 19  loaded_at          15 non-null     datetime64[us]
 20  cutomer_name       15 non-null     str
 21  customer_name      15 non-null     str
dtypes: datetime64[us](3), int64(3), object(3), str(13)
memory usage: 2.7+ KB

In [35]:
pd.read_sql(
    """
    SELECT customer_id, customer_number, customer_status
    FROM dim_customer
    ORDER BY customer_id
    """,
    engine
)

    customer_id customer_number customer_status
0             1      CUST000001        INACTIVE
1             1      CUST000001        INACTIVE
2             2      CUST000002          ACTIVE
3             3      CUST000003          ACTIVE
4             4      CUST000004          ACTIVE
5             5      CUST000005          ACTIVE
6             6      CUST000006          ACTIVE
7             7      CUST000007          ACTIVE
8             8      CUST000008          ACTIVE
9             9      CUST000009          ACTIVE
10           10      CUST000010          ACTIVE
11           11      CUST000011          ACTIVE
12           12      CUST000012        INACTIVE
13           13      CUST000013          ACTIVE
14           14      CUST000014          ACTIVE
15           15      CUST000015          ACTIVE

In [36]:
dim_df = pd.read_sql(
    """
    SELECT
        customer_id,
        customer_number,
        customer_status
    FROM dim_customer
    """,
    engine

)

dim_df

    customer_id customer_number customer_status
0             1      CUST000001        INACTIVE
1             2      CUST000002          ACTIVE
2             3      CUST000003          ACTIVE
3             4      CUST000004          ACTIVE
4             5      CUST000005          ACTIVE
5             6      CUST000006          ACTIVE
6             7      CUST000007          ACTIVE
7             8      CUST000008          ACTIVE
8             9      CUST000009          ACTIVE
9            10      CUST000010          ACTIVE
10           11      CUST000011          ACTIVE
11           12      CUST000012        INACTIVE
12           13      CUST000013          ACTIVE
13           14      CUST000014          ACTIVE
14           15      CUST000015          ACTIVE
15            1      CUST000001        INACTIVE

In [37]:
df[["customer_id", "customer_number", "customer_status"]]

    customer_id customer_number customer_status
0             1      CUST000001        INACTIVE
1             2      CUST000002          ACTIVE
2             3      CUST000003          ACTIVE
3             4      CUST000004          ACTIVE
4             5      CUST000005          ACTIVE
5             6      CUST000006          ACTIVE
6             7      CUST000007          ACTIVE
7             8      CUST000008          ACTIVE
8             9      CUST000009          ACTIVE
9            10      CUST000010          ACTIVE
10           11      CUST000011          ACTIVE
11           12      CUST000012        INACTIVE
12           13      CUST000013          ACTIVE
13           14      CUST000014          ACTIVE
14           15      CUST000015          ACTIVE

In [38]:
merge_df=df.merge(
    dim_df,
    on="customer_id",
    how="inner",
    suffixes=("_stage", "_dw")
)

In [39]:
changed_df = merge_df[
    merge_df["customer_status_stage"]
    != merge_df["customer_status_dw"]
]

In [40]:
changed_df

Empty DataFrame
Columns: [customer_id, customer_number_stage, first_name, middle_name, last_name, date_of_birth, gender, email, phone, customer_type, customer_status_stage, registration_date, risk_category, kyc_status, home_branch_id, created_at, updated_at, source_system, batch_id, loaded_at, cutomer_name, customer_name, customer_number_dw, customer_status_dw]
Index: []

[0 rows x 24 columns]

In [41]:
from sqlalchemy import text

for _, row in changed_df.iterrows():

    with engine.begin() as conn:
        conn.execute(
            text("""
                UPDATE dim_customer
                SET customer_status = :status,
                    updated_at = CURRENT_TIMESTAMP
                WHERE customer_id = :customer_id
                  AND is_current = TRUE
            """),
            {
                "status": row["customer_status_stage"],
                "customer_id": int(row["customer_id"])
            }
        )

In [42]:
pd.read_sql(
    """
    SELECT customer_id, customer_status
    FROM dim_customer
    WHERE customer_id = 1
    """,
    engine
)

   customer_id customer_status
0            1        INACTIVE
1            1        INACTIVE

In [43]:
pd.read_sql(
    """
    SELECT
        customer_id,
        customer_status,
        effective_from,
        effective_to,
        is_current
    FROM dim_customer
    WHERE customer_id = 1;
    """,
    engine
)

   customer_id customer_status effective_from effective_to  is_current
0            1        INACTIVE     2021-06-15   2026-09-02           0
1            1        INACTIVE     2026-09-02   2026-09-02           0

In [44]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(
        text("""
            UPDATE dim_customer
            SET effective_to = CURRENT_DATE,
                is_current = FALSE
            WHERE customer_id = 1
              AND is_current = TRUE;
        """)
    )

In [45]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(
        text("""
            INSERT INTO dim_customer (
                customer_id,
                customer_number,
                customer_name,
                customer_type,
                customer_status,
                risk_category,
                kyc_status,
                branch_id,
                city_id,
                effective_from,
                effective_to,
                is_current
            )
            SELECT
                customer_id,
                customer_number,
                customer_name,
                customer_type,
                'INACTIVE',
                risk_category,
                kyc_status,
                branch_id,
                city_id,
                CURRENT_DATE,
                NULL,
                TRUE
            FROM dim_customer
            WHERE customer_id = 1
              AND is_current = FALSE
            ORDER BY effective_to DESC
            LIMIT 1;
        """)
    )

In [46]:
from sqlalchemy import text

for customer_id in changed_df["customer_id"]:

    with engine.begin() as conn:
        conn.execute(
            text("""
                UPDATE dim_customer
                SET effective_to = CURRENT_DATE,
                    is_current = FALSE
                WHERE customer_id = :customer_id
                  AND is_current = TRUE;
            """),
            {"customer_id": int(customer_id)}
        )

In [47]:
from sqlalchemy import text

for _, row in changed_df.iterrows():

    customer_id = int(row["customer_id"])
    new_status = row["customer_status_stage"]

    with engine.begin() as conn:

        # Get current customer record
        current = conn.execute(
            text("""
                SELECT
                    customer_number,
                    customer_name,
                    customer_type,
                    customer_status,
                    risk_category,
                    kyc_status,
                    branch_id,
                    city_id
                FROM dim_customer
                WHERE customer_id = :customer_id
                  AND is_current = TRUE
                LIMIT 1
            """),
            {"customer_id": customer_id}
        ).mappings().first()

        # If no current record exists, skip
        if current is None:
            print(f"Customer {customer_id}: no current record found")
            continue

        # Expire old version
        conn.execute(
            text("""
                UPDATE dim_customer
                SET effective_to = CURRENT_DATE,
                    is_current = FALSE
                WHERE customer_id = :customer_id
                  AND is_current = TRUE
            """),
            {"customer_id": customer_id}
        )

        # Insert new version
        conn.execute(
            text("""
                INSERT INTO dim_customer (
                    customer_id,
                    customer_number,
                    customer_name,
                    customer_type,
                    customer_status,
                    risk_category,
                    kyc_status,
                    branch_id,
                    city_id,
                    effective_from,
                    effective_to,
                    is_current
                )
                VALUES (
                    :customer_id,
                    :customer_number,
                    :customer_name,
                    :customer_type,
                    :customer_status,
                    :risk_category,
                    :kyc_status,
                    :branch_id,
                    :city_id,
                    CURRENT_DATE,
                    NULL,
                    TRUE
                )
            """),
            {
                "customer_id": customer_id,
                "customer_number": current["customer_number"],
                "customer_name": current["customer_name"],
                "customer_type": current["customer_type"],
                "customer_status": new_status,
                "risk_category": current["risk_category"],
                "kyc_status": current["kyc_status"],
                "branch_id": current["branch_id"],
                "city_id": current["city_id"]
            }
        )

        print(f"Customer {customer_id}: SCD2 updated")

In [48]:
pd.read_sql(
    """
    SELECT
        customer_id,
        customer_number,
        customer_status,
        effective_from,
        effective_to,
        is_current
    FROM dim_customer
    WHERE customer_id = 1
    ORDER BY effective_from;
    """,
    engine
)

,customer_id,customer_number,customer_status,effective_from,effective_to,is_current
0,1,CUST000001,INACTIVE,2021-06-15,2026-09-02,0
1,1,CUST000001,INACTIVE,2026-09-02,2026-09-02,0
2,1,CUST000001,INACTIVE,2026-09-08,None,1

In [49]:
scd2_records = len(changed_df)

print("SCD2 records changed:", scd2_records)

SCD2 records changed: 0

In [50]:
from datetime import datetime
import pandas as pd

scd2_audit_df = pd.DataFrame([{
    "batch_id": 1,
    "pipeline_name": "customer_scd2",
    "source_table": "stg_customers",
    "target_table": "dim_customer",
    "start_time": datetime.now(),
    "end_time": datetime.now(),
    "records_read": len(df),
    "records_loaded": scd2_records,
    "status": "SUCCESS"
}])

scd2_audit_df

,batch_id,pipeline_name,source_table,target_table,start_time,end_time,records_read,records_loaded,status
0,1,customer_scd2,stg_customers,dim_customer,2026-09-08 08:24:03.106075,2026-09-08 08:24:03.106079,15,0,SUCCESS

In [51]:
scd2_audit_df.to_sql(
    "etl_audit",
    con=engine_staging,
    if_exists="append",
    index=False
)

1

In [52]:
pd.read_sql(
    "SHOW TABLES FROM bank_staging;",
    engine_staging
)

    Tables_in_bank_staging
0                etl_audit
1              etl_rejects
2             stg_accounts
3     stg_atm_transactions
4                 stg_atms
5    stg_card_transactions
6                stg_cards
7    stg_customer_accounts
8   stg_customer_addresses
9            stg_customers
10        stg_fraud_alerts
11         stg_kyc_records
12       stg_loan_payments
13               stg_loans
14           stg_merchants
15            stg_payments
16        stg_transactions

In [53]:
customer_lookup = pd.read_sql(
    """
    SELECT
        customer_id,
        account_id
    FROM stg_customer_accounts;
    """,
    engine_staging
)

customer_lookup.head()

   customer_id  account_id
0            1           1
1            2           2
2            3           3
3            4           4
4            5           5

In [54]:
df_lookup = df.merge(
    customer_lookup,
    on="customer_id",
    how="left"
)

df_lookup[[
    "customer_id",
    "account_id"
]].head()

   customer_id  account_id
0            1         1.0
1            1        11.0
2            2         2.0
3            2        11.0
4            3         3.0

In [55]:
account_df = pd.read_sql(
    """
    SELECT
        account_id,
        account_number,
        account_type_id,
        account_status,
        current_balance
    FROM stg_accounts;
    """,
    engine_staging
)

account_load_df = account_df.copy()

account_load_df["effective_from"] = pd.Timestamp.today().date()
account_load_df["effective_to"] = None
account_load_df["is_current"] = True

In [56]:
account_load_df.to_sql(
    "dim_account",
    con=engine,
    if_exists="append",
    index=False
)

11

In [57]:
pd.read_sql(
    "SELECT * FROM dim_account;",
    engine
)

,account_key,account_id,account_number,account_type_id,account_status,current_balance,effective_from,effective_to,is_current,created_at,updated_at
0,1,1,AC10000001,1,ACTIVE,250000.0,2026-09-08,None,1,2026-09-08 08:25:29,2026-09-08 08:25:29
1,2,2,AC10000002,1,ACTIVE,85000.0,2026-09-08,None,1,2026-09-08 08:25:29,2026-09-08 08:25:29
2,3,3,AC10000003,2,ACTIVE,750000.0,2026-09-08,None,1,2026-09-08 08:25:29,2026-09-08 08:25:29
3,4,4,AC10000004,1,ACTIVE,450000.0,2026-09-08,None,1,2026-09-08 08:25:29,2026-09-08 08:25:29
4,5,5,AC10000005,3,ACTIVE,62000.0,2026-09-08,None,1,2026-09-08 08:25:29,2026-09-08 08:25:29
5,6,6,AC10000006,1,ACTIVE,15000.0,2026-09-08,None,1,2026-09-08 08:25:29,2026-09-08 08:25:29
6,7,7,AC10000007,6,ACTIVE,500000.0,2026-09-08,None,1,2026-09-08 08:25:29,2026-09-08 08:25:29
7,8,8,AC10000008,1,ACTIVE,95000.0,2026-09-08,None,1,2026-09-08 08:25:29,2026-09-08 08:25:29
8,9,9,AC10000009,4,ACTIVE,1250000.0,2026-09-08,None,1,2026-09-08 08:25:29,2026-09-08 08:25:29
9,10,10,AC10000010,5,ACTIVE,300000.0,2026-09-08,None,1,2026-09-08 08:25:29,2026-09-08 08:25:29
10,11,11,AC10000011,1,ACTIVE,180000.0,2026-09-08,None,1,2026-09-08 08:25:29,2026-09-08 08:25:29

In [59]:
merchant_df = pd.read_sql(
    """
    SELECT
        merchant_id,
        merchant_name,
        merchant_category,
        city_id
    FROM stg_merchants;
    """,
    engine_staging
)

merchant_df.to_sql(
    "dim_merchant",
    con=engine,
    if_exists="append",
    index=False
)

10

In [60]:
merchant_df = pd.read_sql(
    """
    SELECT
        merchant_id,
        merchant_name,
        merchant_category,
        city_id
    FROM stg_merchants;
    """,
    engine_staging
)

merchant_df.to_sql(
    "dim_merchant",
    con=engine,
    if_exists="append",
    index=False
)

10

In [61]:
card_df = pd.read_sql(
    """
    SELECT
        card_id,
        card_number,
        card_type,
        card_status,
        issue_date,
        expiry_date,
        account_id
    FROM stg_cards;
    """,
    engine_staging
)

DatabaseError: Execution failed on sql '
    SELECT
        card_id,
        card_number,
        card_type,
        card_status,
        issue_date,
        expiry_date,
        account_id
    FROM stg_cards;
    ': (mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'card_number' in 'field list'
[SQL:
    SELECT
        card_id,
        card_number,
        card_type,
        card_status,
        issue_date,
        expiry_date,
        account_id
    FROM stg_cards;
    ]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [64]:
card_df = pd.read_sql(
    """
    SELECT
        card_id,
        masked_card_number AS card_number,
        card_type,
        card_status,
        issue_date,
        expiry_date,
        account_id
    FROM stg_cards;
    """,
    engine_staging
)

card_df.to_sql(
    "dim_card",
    con=engine,
    if_exists="append",
    index=False
)

print("dim_card loaded:", len(card_df))

dim_card loaded: 5

In [63]:
pd.read_sql(
    "DESCRIBE stg_cards;",
    engine_staging
)

,Field,Type,Null,Key,Default,Extra
0,card_id,bigint,YES,,NaN,
1,card_number_hash,varchar(128),YES,,NaN,
2,masked_card_number,varchar(25),YES,,NaN,
3,customer_id,bigint,YES,,NaN,
4,account_id,bigint,YES,,NaN,
5,card_type,varchar(30),YES,,NaN,
6,card_network,varchar(30),YES,,NaN,
7,issue_date,date,YES,,NaN,
8,expiry_date,date,YES,,NaN,
9,card_status,varchar(30),YES,,NaN,
10,credit_limit,"decimal(18,2)",YES,,NaN,
11,available_limit,"decimal(18,2)",YES,,NaN,
12,created_at,timestamp,YES,,NaN,
13,source_system,varchar(50),YES,,NaN,
14,batch_id,bigint,YES,,NaN,
15,loaded_at,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED

In [65]:
pd.read_sql(
    "DESCRIBE stg_transactions;",
    engine_staging
)

,Field,Type,Null,Key,Default,Extra
0,transaction_id,bigint,YES,,NaN,
1,transaction_reference,varchar(50),YES,,NaN,
2,account_id,bigint,YES,,NaN,
3,transaction_type_id,int,YES,,NaN,
4,transaction_date,datetime,YES,,NaN,
5,debit_amount,"decimal(18,2)",YES,,NaN,
6,credit_amount,"decimal(18,2)",YES,,NaN,
7,balance_after_transaction,"decimal(18,2)",YES,,NaN,
8,currency_code,varchar(10),YES,,NaN,
9,channel,varchar(30),YES,,NaN,
10,counterparty_account_id,bigint,YES,,NaN,
11,transaction_status,varchar(30),YES,,NaN,
12,remarks,varchar(255),YES,,NaN,
13,source_system,varchar(50),YES,,NaN,
14,batch_id,bigint,YES,,NaN,
15,loaded_at,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED

In [66]:
import pandas as pd

# 1. Read transactions from staging
transaction_df = pd.read_sql(
    """
    SELECT
        transaction_id,
        account_id,
        transaction_type_id,
        transaction_date,
        debit_amount,
        credit_amount,
        transaction_status
    FROM stg_transactions;
    """,
    engine_staging
)

# 2. Create transaction amount
transaction_df["amount"] = (
    transaction_df["debit_amount"].fillna(0)
    + transaction_df["credit_amount"].fillna(0)
)

# 3. Lookup customer_id from account_id
customer_account_lookup = pd.read_sql(
    """
    SELECT
        account_id,
        customer_id
    FROM stg_customer_accounts;
    """,
    engine_staging
)

transaction_df = transaction_df.merge(
    customer_account_lookup,
    on="account_id",
    how="left"
)

# 4. Lookup account_key
account_lookup = pd.read_sql(
    """
    SELECT
        account_id,
        account_key
    FROM dim_account
    WHERE is_current = TRUE;
    """,
    engine
)

transaction_df = transaction_df.merge(
    account_lookup,
    on="account_id",
    how="left"
)

# 5. Lookup customer_key
customer_lookup = pd.read_sql(
    """
    SELECT
        customer_id,
        customer_key
    FROM dim_customer
    WHERE is_current = TRUE;
    """,
    engine
)

transaction_df = transaction_df.merge(
    customer_lookup,
    on="customer_id",
    how="left"
)

# 6. Create date_key as YYYYMMDD
transaction_df["date_key"] = pd.to_datetime(
    transaction_df["transaction_date"]
).dt.strftime("%Y%m%d").astype(int)

# 7. Prepare final fact dataframe
fact_transaction_df = transaction_df[
    [
        "transaction_id",
        "customer_key",
        "account_key",
        "date_key",
        "transaction_date",
        "amount",
        "transaction_status"
    ]
].copy()

# transaction_type_key is left NULL because
# dim_transaction_type has not been loaded yet.
fact_transaction_df["transaction_type_key"] = None

# Put columns in warehouse order
fact_transaction_df = fact_transaction_df[
    [
        "transaction_id",
        "customer_key",
        "account_key",
        "transaction_type_key",
        "date_key",
        "transaction_date",
        "amount",
        "transaction_status"
    ]
]

# 8. Load into warehouse
fact_transaction_df.to_sql(
    "fact_transactions",
    con=engine,
    if_exists="append",
    index=False
)

print("fact_transactions loaded:", len(fact_transaction_df))

fact_transactions loaded: 10

In [67]:
pd.read_sql(
    "DESCRIBE stg_payments;",
    engine_staging
)

,Field,Type,Null,Key,Default,Extra
0,payment_id,bigint,YES,,NaN,
1,payment_reference,varchar(50),YES,,NaN,
2,transaction_id,bigint,YES,,NaN,
3,customer_id,bigint,YES,,NaN,
4,payment_method_id,int,YES,,NaN,
5,payment_date,datetime,YES,,NaN,
6,amount,"decimal(18,2)",YES,,NaN,
7,currency_code,varchar(10),YES,,NaN,
8,payment_status,varchar(30),YES,,NaN,
9,external_reference,varchar(100),YES,,NaN,
10,failure_reason,varchar(255),YES,,NaN,
11,source_system,varchar(50),YES,,NaN,
12,batch_id,bigint,YES,,NaN,
13,loaded_at,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED

In [71]:
transaction_lookup = pd.read_sql(
    """
    SELECT
        transaction_id,
        transaction_key
    FROM bank_dw.fact_transactions;
    """,
    engine
)

transaction_lookup.head()

   transaction_id  transaction_key
0               1                1
1               2                2
2               3                3
3               4                4
4               5                5

In [69]:
pd.read_sql(
    "DESCRIBE fact_transactions;",
    engine
)

,Field,Type,Null,Key,Default,Extra
0,transaction_key,bigint,NO,PRI,NaN,auto_increment
1,transaction_id,bigint,NO,,NaN,
2,customer_key,bigint,YES,,NaN,
3,account_key,bigint,YES,,NaN,
4,transaction_type_key,bigint,YES,,NaN,
5,date_key,int,YES,,NaN,
6,transaction_date,datetime,YES,,NaN,
7,amount,"decimal(18,2)",YES,,NaN,
8,transaction_status,varchar(30),YES,,NaN,
9,created_at,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED

In [70]:
import pandas as pd

# 1. Read payments from staging
payment_df = pd.read_sql(
    """
    SELECT
        payment_id,
        transaction_id,
        payment_date,
        amount,
        payment_status
    FROM stg_payments;
    """,
    engine_staging
)

# 2. LOOKUP: transaction_id -> transaction_key
transaction_lookup = pd.read_sql(
    """
    SELECT
        transaction_id,
        transaction_key
    FROM fact_transactions;
    """,
    engine
)

payment_df = payment_df.merge(
    transaction_lookup,
    on="transaction_id",
    how="left"
)

# 3. LOOKUP: payment_date -> date_key
payment_df["date_key"] = pd.to_datetime(
    payment_df["payment_date"]
).dt.strftime("%Y%m%d").astype(int)

# 4. payment_method_key unavailable for now
payment_df["payment_method_key"] = None

# 5. Prepare warehouse columns
fact_payment_df = payment_df[
    [
        "payment_id",
        "transaction_key",
        "payment_method_key",
        "date_key",
        "payment_date",
        "amount",
        "payment_status"
    ]
].copy()

# 6. Load
fact_payment_df.to_sql(
    "fact_payments",
    con=engine,
    if_exists="append",
    index=False
)

print("Payments loaded:", len(fact_payment_df))
print("Transaction lookup failures:",
      fact_payment_df["transaction_key"].isna().sum())

Payments loaded: 8
Transaction lookup failures: 0

In [72]:
payment_df = pd.read_sql(
    """
    SELECT
        payment_id,
        transaction_id,
        payment_date,
        amount,
        payment_status
    FROM stg_payments;
    """,
    engine_staging
)

payment_df = payment_df.merge(
    transaction_lookup,
    on="transaction_id",
    how="left"
)

payment_df["date_key"] = pd.to_datetime(
    payment_df["payment_date"]
).dt.strftime("%Y%m%d").astype(int)

payment_df["payment_method_key"] = None

fact_payment_df = payment_df[
    [
        "payment_id",
        "transaction_key",
        "payment_method_key",
        "date_key",
        "payment_date",
        "amount",
        "payment_status"
    ]
]

print(fact_payment_df)
print("Lookup failures:",
      fact_payment_df["transaction_key"].isna().sum())

   payment_id  transaction_key payment_method_key  date_key  \
0           1                1               None  20260105
1           2                2               None  20260106
2           3                3               None  20260106
3           4                4               None  20260108
4           5                5               None  20260110
5           6                6               None  20260112
6           7                7               None  20260115
7           8                8               None  20260118

         payment_date    amount payment_status
0 2026-01-05 10:15:05   50000.0        SUCCESS
1 2026-01-06 11:30:05    5000.0        SUCCESS
2 2026-01-06 11:30:07    5000.0        SUCCESS
3 2026-01-08 09:45:05   25000.0        SUCCESS
4 2026-01-10 14:20:05  100000.0        SUCCESS
5 2026-01-12 16:10:05   10000.0        SUCCESS
6 2026-01-15 19:30:05    2500.0        SUCCESS
7 2026-01-18 12:00:05   50000.0        SUCCESS
Lookup failures: 0

In [73]:
fact_payment_df.to_sql(
    "fact_payments",
    con=engine,
    if_exists="append",
    index=False
)

print("fact_payments loaded:", len(fact_payment_df))

fact_payments loaded: 8

In [74]:
pd.read_sql(
    """
    SELECT
        payment_id,
        transaction_key,
        date_key,
        payment_date,
        amount,
        payment_status
    FROM fact_payments;
    """,
    engine
)

,payment_id,transaction_key,date_key,payment_date,amount,payment_status
0,1,1,20260105,2026-01-05 10:15:05,50000.0,SUCCESS
1,2,2,20260106,2026-01-06 11:30:05,5000.0,SUCCESS
2,3,3,20260106,2026-01-06 11:30:07,5000.0,SUCCESS
3,4,4,20260108,2026-01-08 09:45:05,25000.0,SUCCESS
4,5,5,20260110,2026-01-10 14:20:05,100000.0,SUCCESS
5,6,6,20260112,2026-01-12 16:10:05,10000.0,SUCCESS
6,7,7,20260115,2026-01-15 19:30:05,2500.0,SUCCESS
7,8,8,20260118,2026-01-18 12:00:05,50000.0,SUCCESS
8,1,1,20260105,2026-01-05 10:15:05,50000.0,SUCCESS
9,2,2,20260106,2026-01-06 11:30:05,5000.0,SUCCESS
10,3,3,20260106,2026-01-06 11:30:07,5000.0,SUCCESS
11,4,4,20260108,2026-01-08 09:45:05,25000.0,SUCCESS
12,5,5,20260110,2026-01-10 14:20:05,100000.0,SUCCESS
13,6,6,20260112,2026-01-12 16:10:05,10000.0,SUCCESS
14,7,7,20260115,2026-01-15 19:30:05,2500.0,SUCCESS
15,8,8,20260118,2026-01-18 12:00:05,50000.0,SUCCESS

In [75]:
tables = [
    "dim_customer",
    "dim_account",
    "dim_merchant",
    "dim_card",
    "fact_transactions",
    "fact_payments"
]

for table in tables:
    count = pd.read_sql(
        f"SELECT COUNT(*) AS cnt FROM {table};",
        engine
    ).iloc[0]["cnt"]

    print(f"{table}: {count}")

dim_customer: 17
dim_account: 11
dim_merchant: 30
dim_card: 5
fact_transactions: 10
fact_payments: 16